const fs = require('fs');

const code = `import React, { useState, useEffect, useMemo, useRef } from 'react';
import { 
  LineChart, Line, BarChart, Bar, PieChart, Pie, Cell, AreaChart, Area, 
  XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Legend, ResponsiveContainer, ReferenceLine
} from 'recharts';
import { 
  Bell, Check, ChevronDown, Edit2, Eye, EyeOff, LayoutDashboard, ListTodo,
  LogOut, PieChart as PieChartIcon, Plus, Search, Settings as SettingsIcon, Target, Trash2,
  TrendingDown, TrendingUp, Upload, Download, Wallet, AlertCircle, Calendar,
  CreditCard, DollarSign, ArrowUpRight, ArrowDownRight, Activity, FileText,
  Filter, Tag, ChevronsUpDown, CheckCircle2, Clock, X, Circle, HelpCircle,
  Lightbulb, AlertTriangle, ShieldCheck
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  format, subDays, subMonths, isSameMonth, parseISO, isAfter, isBefore, 
  startOfMonth, endOfMonth, eachDayOfInterval, formatDistanceToNow, isFuture, getDay, startOfWeek, addDays,
  parse
} from 'date-fns';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

// ==========================================
// TYPES
// ==========================================
export type TransactionType = 'Income' | 'Expense';
export type PaymentMethod = 'Cash' | 'Bank Transfer' | 'Credit Card' | 'Debit Card' | 'Mobile Wallet' | 'Cheque' | 'Other';

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  category: string;
  title: string;
  date: string; // ISO
  paymentMethod: PaymentMethod;
  notes?: string;
  recurring: boolean;
  recurringFrequency?: 'Daily' | 'Weekly' | 'Monthly' | 'Yearly';
  tags: string[];
}

export interface User { id: string; name: string; email: string; joinedDate: string; }
export interface Budget { category: string; limit: number; }
export interface Task { id: string; title: string; priority: 'Low' | 'Medium' | 'High'; dueDate: string; status: 'Pending' | 'In Progress' | 'Done'; isAutoGenerated?: boolean; }
export interface SettingsConfig { currency: string; dateFormat: string; theme: 'Dark' | 'Light' | 'System'; defaultView: string; alertThreshold: number; budgetAlerts: boolean; categories: { income: string[]; expense: string[] }; }
export interface Notification { id: string; message: string; date: string; read: boolean; type: 'info' | 'warning' | 'success'; }

// ==========================================
// CONSTANTS & DEMO DATA
// ==========================================
export const DEFAULT_INCOME_CATS = ['Salary', 'Freelance', 'Business', 'Investment Returns', 'Rental Income', 'Gift', 'Bonus', 'Other Income'];
export const DEFAULT_EXPENSE_CATS = ['Food & Dining', 'Transport', 'Housing/Rent', 'Utilities', 'Healthcare', 'Education', 'Entertainment', 'Shopping', 'Personal Care', 'Savings/Investment', 'Subscriptions', 'Travel', 'Debt Payment', 'Other Expense'];
export const CURRENCIES = ['PKR ₨', 'USD $', 'EUR €', 'GBP £', 'SAR ﷼', 'AED د.إ.'];

const generateDemoData = () => {
  const txs: Transaction[] = [];
  const today = new Date();
  for (let i = 0; i < 180; i++) {
    const date = subDays(today, i);
    const dateStr = date.toISOString();
    if (i % 30 === 0) {
      txs.push({ id: \`demo-inc-\${i}\`, type: 'Income', amount: 150000, category: 'Salary', title: 'Monthly Salary', date: dateStr, paymentMethod: 'Bank Transfer', recurring: true, recurringFrequency: 'Monthly', tags: ['work'] });
    }
    txs.push({ id: \`demo-food-\${i}\`, type: 'Expense', amount: 500 + Math.floor(Math.random() * 2000), category: 'Food & Dining', title: 'Groceries/Meals', date: dateStr, paymentMethod: 'Credit Card', recurring: false, tags: ['daily'] });
    if (i % 3 === 0) {
      txs.push({ id: \`demo-trans-\${i}\`, type: 'Expense', amount: 300 + Math.floor(Math.random() * 1000), category: 'Transport', title: 'Fuel/Ride', date: dateStr, paymentMethod: 'Mobile Wallet', recurring: false, tags: ['commute'] });
    }
    if (i % 30 === 5) {
      txs.push({ id: \`demo-rent-\${i}\`, type: 'Expense', amount: 40000, category: 'Housing/Rent', title: 'Rent Payment', date: dateStr, paymentMethod: 'Bank Transfer', recurring: true, recurringFrequency: 'Monthly', tags: ['housing'] });
      txs.push({ id: \`demo-util-\${i}\`, type: 'Expense', amount: 12000, category: 'Utilities', title: 'Electricity & Water', date: dateStr, paymentMethod: 'Bank Transfer', recurring: true, recurringFrequency: 'Monthly', tags: ['bills'] });
    }
    if (i % 30 === 10) {
      txs.push({ id: \`demo-sub-\${i}\`, type: 'Expense', amount: 1500, category: 'Subscriptions', title: 'Netflix', date: dateStr, paymentMethod: 'Credit Card', recurring: true, recurringFrequency: 'Monthly', tags: ['fun'] });
      txs.push({ id: \`demo-sub2-\${i}\`, type: 'Expense', amount: 800, category: 'Subscriptions', title: 'Spotify', date: dateStr, paymentMethod: 'Credit Card', recurring: true, recurringFrequency: 'Monthly', tags: ['fun'] });
    }
    if (i % 14 === 0) {
      txs.push({ id: \`demo-ent-\${i}\`, type: 'Expense', amount: 3000 + Math.floor(Math.random() * 5000), category: 'Entertainment', title: 'Movie & Dinner', date: dateStr, paymentMethod: 'Debit Card', recurring: false, tags: ['fun'] });
    }
  }
  return txs;
};

export const formatCurrency = (amount: number, currency: string) => {
  const symbol = currency.split(' ')[1] || '$';
  return \`\${amount < 0 ? '-' : ''}\${symbol}\${Math.abs(amount).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 })}\`; // Using specific grouping can be done via options
};

export const COLORS = {
  income: '#10b981', // emerald-500
  expense: '#f43f5e', // coral-500
  accent: '#f59e0b', // amber-500
  slate: '#334155',
  bg: '#0f172a',
  surface: '#151f32',
};

const CHART_COLORS = ['#34d399', '#60a5fa', '#a78bfa', '#fb7185', '#fcd34d', '#2dd4bf'];

// ==========================================
// MAIN APP
// ==========================================
export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [budgets, setBudgets] = useState<Budget[]>([
    { category: 'Food & Dining', limit: 25000 },
    { category: 'Transport', limit: 10000 },
    { category: 'Entertainment', limit: 8000 }
  ]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [settings, setSettings] = useState<SettingsConfig>({
    currency: 'PKR ₨',
    dateFormat: 'DD/MM/YYYY',
    theme: 'Dark',
    defaultView: 'Dashboard',
    alertThreshold: 1000000,
    budgetAlerts: true,
    categories: { income: DEFAULT_INCOME_CATS, expense: DEFAULT_EXPENSE_CATS }
  });

  const [activeTab, setActiveTab] = useState('Dashboard');
  const [isAuthMode, setIsAuthMode] = useState<'Login' | 'Register'>('Login');
  
  // Modals state
  const [isSidebarOpen, setIsSidebarOpen] = useState(false);
  const [isTxModalOpen, setIsTxModalOpen] = useState(false);
  const [editingTx, setEditingTx] = useState<Transaction | null>(null);
  const [toasts, setToasts] = useState<{id: string, msg: string, type: 'success'|'error'|'info'}[]>([]);

  const addToast = (msg: string, type: 'success'|'error'|'info' = 'info') => {
    const id = Math.random().toString(36).substr(2, 9);
    setToasts(prev => [...prev, {id, msg, type}]);
    setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 4000);
  };

  const loginDemo = () => {
    setUser({ id: 'demo123', name: 'Alex Demo', email: 'alex@finflow.demo', joinedDate: new Date().toISOString() });
    setTransactions(generateDemoData());
    addToast('Logged in with Demo Account', 'success');
  };

  // Auth Submit Handlers
  const handleAuth = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    const email = data.get('email') as string;
    const name = data.get('name') as string || 'New User';
    setUser({ id: 'usr-'+Date.now(), name, email, joinedDate: new Date().toISOString() });
    if(transactions.length === 0) setTransactions([]); // Empty initially unless demo
    addToast(\`Welcome to FinFlow, \${name}!\`, 'success');
  };

  const logout = () => {
    setUser(null);
    setTransactions([]);
    setTasks([]);
    addToast('Logged out successfully', 'info');
  };

  // derived state
  const thisMonthTxs = useMemo(() => {
    const start = startOfMonth(new Date());
    const end = endOfMonth(new Date());
    return transactions.filter(t => isAfter(parseISO(t.date), start) && isBefore(parseISO(t.date), end));
  }, [transactions]);

  const totalIncome = useMemo(() => transactions.filter(t => t.type === 'Income').reduce((a, b) => a + b.amount, 0), [transactions]);
  const totalExpense = useMemo(() => transactions.filter(t => t.type === 'Expense').reduce((a, b) => a + b.amount, 0), [transactions]);
  const netBalance = totalIncome - totalExpense;

  const monthlyIncome = useMemo(() => thisMonthTxs.filter(t => t.type === 'Income').reduce((a, b) => a + b.amount, 0), [thisMonthTxs]);
  const monthlyExpense = useMemo(() => thisMonthTxs.filter(t => t.type === 'Expense').reduce((a, b) => a + b.amount, 0), [thisMonthTxs]);
  const savingsRate = monthlyIncome > 0 ? ((monthlyIncome - monthlyExpense) / monthlyIncome) * 100 : 0;

  // Render Auth
  if (!user) {
    return (
      <div className="min-h-screen bg-slate-900 text-slate-100 flex items-center justify-center p-4">
        <div className="max-w-md w-full bg-slate-850 p-8 rounded-2xl shadow-2xl border border-slate-800">
          <div className="text-center mb-8">
             <div className="w-16 h-16 bg-emerald-500/10 rounded-2xl mx-auto flex items-center justify-center mb-4">
               <Wallet className="w-8 h-8 text-emerald-500" />
             </div>
             <h1 className="text-3xl font-display font-bold text-white tracking-tight">FinFlow</h1>
             <p className="text-slate-400 mt-2">Take control of your financial future.</p>
          </div>

          <form onSubmit={handleAuth} className="space-y-4">
            <div className="flex bg-slate-800 p-1 rounded-lg mb-6">
              <button type="button" onClick={() => setIsAuthMode('Login')} className={cn("flex-1 py-2 text-sm font-medium rounded-md transition-all", isAuthMode === 'Login' ? 'bg-slate-700 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200')}>Login</button>
              <button type="button" onClick={() => setIsAuthMode('Register')} className={cn("flex-1 py-2 text-sm font-medium rounded-md transition-all", isAuthMode === 'Register' ? 'bg-slate-700 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200')}>Register</button>
            </div>

            {isAuthMode === 'Register' && (
              <div>
                <label className="block text-sm text-slate-400 mb-1">Full Name</label>
                <input required name="name" type="text" className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500 transition-colors" placeholder="Jane Doe" />
              </div>
            )}
            <div>
              <label className="block text-sm text-slate-400 mb-1">Email</label>
              <input required name="email" type="email" className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500 transition-colors" placeholder="jane@example.com" />
            </div>
            <div>
              <label className="block text-sm text-slate-400 mb-1">Password</label>
              <input required name="password" minLength={8} type="password" className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500 transition-colors" placeholder="••••••••" />
            </div>
            {isAuthMode === 'Register' && (
               <div>
                 <label className="block text-sm text-slate-400 mb-1">Confirm Password</label>
                 <input required name="confirmPassword" minLength={8} type="password" className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500 transition-colors" placeholder="••••••••" />
               </div>
            )}
            
            <button type="submit" className="w-full bg-emerald-500 hover:bg-emerald-600 text-slate-900 font-bold py-3 rounded-xl transition-all shadow-lg shadow-emerald-500/20 mt-4">
              {isAuthMode === 'Login' ? 'Sign In' : 'Create Account'}
            </button>
          </form>

          <div className="mt-8 relative">
            <div className="absolute inset-0 flex items-center"><div className="w-full border-t border-slate-800"></div></div>
            <div className="relative flex justify-center text-xs text-slate-500"><span className="bg-slate-850 px-2">OR</span></div>
          </div>

          <button onClick={loginDemo} type="button" className="w-full mt-6 bg-slate-800 hover:bg-slate-700 text-slate-200 font-medium py-3 rounded-xl transition-all border border-slate-700 flex items-center justify-center gap-2">
            <Activity className="w-4 h-4" /> Try Demo Account
          </button>
        </div>
        
        {/* Toasts rendered here for auth */}
        <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">
          <AnimatePresence>
            {toasts.map(t => (
              <motion.div key={t.id} initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} exit={{opacity:0, scale:0.95}} className={cn("px-4 py-3 rounded-xl shadow-lg border flex items-center gap-3", t.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : t.type === 'error' ? 'bg-coral-500/10 border-coral-500/20 text-coral-400' : 'bg-slate-800 border-slate-700 text-slate-200')}>
                {t.type === 'success' ? <CheckCircle2 className="w-5 h-5"/> : t.type==='error' ? <AlertCircle className="w-5 h-5"/> : <Bell className="w-5 h-5"/>}
                 {t.msg}
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      </div>
    );
  }

  // Determine greeting
  const hour = new Date().getHours();
  const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';

  const NavItem = ({ icon: Icon, label, id }: { icon: any, label: string, id: string }) => (
    <button onClick={() => setActiveTab(id)} className={cn("flex items-center gap-3 w-full px-4 py-3 rounded-xl transition-all text-left", activeTab === id ? 'bg-emerald-500/10 text-emerald-400 font-medium' : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200')}>
      <Icon className="w-5 h-5" />
      {label}
    </button>
  );

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex font-body">
      {/* Sidebar */}
      <aside className="w-64 bg-slate-850 border-r border-slate-800 hidden md:flex flex-col">
        <div className="p-6 flex items-center gap-3">
          <div className="w-8 h-8 flex items-center justify-center bg-emerald-500 rounded-lg">
            <Wallet className="w-5 h-5 text-slate-900" />
          </div>
          <span className="font-display font-bold text-xl tracking-tight text-white">FinFlow</span>
        </div>
        
        <nav className="flex-1 px-4 space-y-1 mt-4">
          <NavItem icon={LayoutDashboard} label="Dashboard" id="Dashboard" />
          <NavItem icon={ListTodo} label="Transactions" id="Transactions" />
          <NavItem icon={PieChartIcon} label="Charts & Analytics" id="Charts" />
          <NavItem icon={Lightbulb} label="AI Insights" id="Insights" />
          <NavItem icon={Target} label="Budget Planner" id="Budgets" />
          <NavItem icon={CheckCircle2} label="Goals & Tasks" id="Tasks" />
        </nav>

        <div className="p-4 border-t border-slate-800">
           <NavItem icon={SettingsIcon} label="Settings" id="Settings" />
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col h-screen overflow-hidden">
        {/* Top Navbar */}
        <header className="h-16 border-b border-slate-800 bg-slate-850/50 backdrop-blur-md flex items-center justify-between px-6 shrink-0 z-10 w-full">
          <div className="flex items-center gap-3">
            <h2 className="text-lg font-medium text-slate-200">{greeting}, {user.name.split(' ')[0]} 👋</h2>
          </div>
          <div className="flex items-center gap-4">
            <button className="relative p-2 text-slate-400 hover:text-slate-200 transition-colors">
              <Bell className="w-5 h-5" />
              {notifications.filter(n => !n.read).length > 0 && (
                <span className="absolute top-1 right-1 w-2 h-2 bg-coral-500 rounded-full" />
              )}
            </button>
            <div className="h-6 w-px bg-slate-700"></div>
            <div className="flex items-center gap-3 group relative cursor-pointer" onClick={logout}>
              <div className="w-8 h-8 rounded-full bg-slate-700 flex items-center justify-center text-sm font-medium text-slate-200">
                {user.name.charAt(0).toUpperCase()}
              </div>
              <LogOut className="w-4 h-4 text-slate-500 group-hover:text-coral-400 transition-colors" />
            </div>
          </div>
        </header>

        {/* Scrollable Area */}
        <div className="flex-1 overflow-auto p-4 md:p-8">
           <div className="max-w-7xl mx-auto space-y-8">
             {activeTab === 'Dashboard' && (
                <DashboardView 
                  user={user}
                  transactions={transactions} 
                  settings={settings} 
                  monthlyIncome={monthlyIncome} 
                  monthlyExpense={monthlyExpense} 
                  netBalance={netBalance} 
                  savingsRate={savingsRate}
                  setTab={setActiveTab}
                />
             )}
             {activeTab === 'Transactions' && (
                <TransactionsView transactions={transactions} settings={settings} onAdd={() => {setEditingTx(null); setIsTxModalOpen(true)}} onEdit={(tx) => {setEditingTx(tx); setIsTxModalOpen(true)}} onDelete={(id) => {
                  setTransactions(prev => prev.filter(t => t.id !== id));
                  addToast('Transaction deleted', 'success');
                }} />
             )}
             {
               activeTab === 'Charts' && (
                 <ChartsView transactions={transactions} settings={settings} />
               )
             }
             {
               activeTab === 'Insights' && (
                 <InsightsView transactions={transactions} settings={settings} />
               )
             }
             {
               activeTab === 'Budgets' && (
                 <BudgetsView transactions={transactions} settings={settings} budgets={budgets} setBudgets={setBudgets} />
               )
             }
             {
               activeTab === 'Tasks' && (
                 <TasksView transactions={transactions} tasks={tasks} setTasks={setTasks} />
               )
             }
             {
               activeTab === 'Settings' && (
                 <SettingsView settings={settings} setSettings={setSettings} user={user} setTransactions={setTransactions} addToast={addToast} />
               )
             }
           </div>
        </div>
      </main>

      {/* Transaction Modal */}
      <AnimatePresence>
        {isTxModalOpen && (
          <TransactionModal 
            editingTx={editingTx}
            settings={settings}
            onClose={() => setIsTxModalOpen(false)}
            onSave={(tx) => {
              if (editingTx) {
                setTransactions(prev => prev.map(t => t.id === tx.id ? tx : t));
                addToast('Transaction updated', 'success');
              } else {
                setTransactions(prev => [tx, ...prev]);
                addToast('Transaction added', 'success');
              }
              setIsTxModalOpen(false);
            }}
          />
        )}
      </AnimatePresence>

      {/* Toasts */}
      <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">
        <AnimatePresence>
          {toasts.map(t => (
            <motion.div key={t.id} initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} exit={{opacity:0, scale:0.95}} className={cn("px-4 py-3 rounded-xl shadow-lg border flex items-center gap-3", t.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : t.type === 'error' ? 'bg-coral-500/10 border-coral-500/20 text-coral-400' : 'bg-slate-800 border-slate-700 text-slate-200')}>
              {t.type === 'success' ? <CheckCircle2 className="w-5 h-5"/> : t.type==='error' ? <AlertCircle className="w-5 h-5"/> : <Bell className="w-5 h-5"/>}
               {t.msg}
            </motion.div>
          ))}
        </AnimatePresence>
      </div>

    </div>
  );
}

// ==========================================
// FEATURE VIEWS
// ==========================================

function DashboardView({ user, transactions, settings, monthlyIncome, monthlyExpense, netBalance, savingsRate, setTab }: any) {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-display font-semibold">Overview</h1>
        <button onClick={() => setTab('Transactions')} className="bg-emerald-500 hover:bg-emerald-600 text-slate-900 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors">
          <Plus className="w-4 h-4" /> Add Record
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <SummaryCard title="Total Balance" amount={netBalance} trend={5.2} isPositive={netBalance >= 0} currency={settings.currency} icon={Wallet} />
        <SummaryCard title="Monthly Income" amount={monthlyIncome} trend={12} isPositive={true} currency={settings.currency} icon={TrendingUp} />
        <SummaryCard title="Monthly Expenses" amount={monthlyExpense} trend={-2.4} isPositive={false} currency={settings.currency} icon={TrendingDown} />
        <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 relative overflow-hidden flex flex-col justify-between">
          <div className="flex justify-between items-start">
            <span className="text-sm text-slate-400 font-medium tracking-wide">Savings Rate</span>
            <Target className="w-5 h-5 text-amber-500" />
          </div>
          <div className="mt-4 flex items-end justify-between">
             <div className="text-3xl font-mono font-semibold text-white">{savingsRate.toFixed(1)}%</div>
          </div>
          <p className="text-xs text-slate-500 mt-2">Target: 20%</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
         <div className="bg-slate-850 shrink-0 p-6 rounded-2xl border border-slate-800 lg:col-span-2 shadow-sm min-h-[400px] flex flex-col">
            <div className="flex justify-between items-center mb-6">
               <h3 className="text-lg font-medium">Recent Cash Flow</h3>
               <button onClick={() => setTab('Charts')} className="text-sm text-emerald-400 hover:text-emerald-300">View detailed</button>
            </div>
            <div className="flex-1 w-full relative">
              {transactions.length === 0 ? (
                 <EmptyState message="No transactions to chart" />
              ) : (
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={getDailyCashflowProps(transactions)}>
                    <defs>
                      <linearGradient id="colorInc" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor={COLORS.income} stopOpacity={0.3}/>
                        <stop offset="95%" stopColor={COLORS.income} stopOpacity={0}/>
                      </linearGradient>
                      <linearGradient id="colorExp" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor={COLORS.expense} stopOpacity={0.3}/>
                        <stop offset="95%" stopColor={COLORS.expense} stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                    <XAxis dataKey="date" stroke="#475569" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis stroke="#475569" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(v) => \`\${v/1000}k\`} />
                    <RechartsTooltip contentStyle={{backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: '8px'}} itemStyle={{fontFamily: 'IBM Plex Mono'}} />
                    <Area type="monotone" dataKey="Income" stroke={COLORS.income} fillOpacity={1} fill="url(#colorInc)" />
                    <Area type="monotone" dataKey="Expense" stroke={COLORS.expense} fillOpacity={1} fill="url(#colorExp)" />
                  </AreaChart>
                </ResponsiveContainer>
              )}
            </div>
         </div>
         
         <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 shadow-sm flex flex-col">
            <h3 className="text-lg font-medium mb-4">Recent Transactions</h3>
            <div className="space-y-4 flex-1 overflow-y-auto pr-2">
              {transactions.slice(0, 7).map(tx => (
                <div key={tx.id} className="flex justify-between items-center bg-slate-900/50 p-3 rounded-xl border border-slate-800/80 hover:border-slate-700 transition-colors">
                  <div className="flex gap-3 items-center">
                    <div className={cn("w-10 h-10 rounded-full flex items-center justify-center shrink-0", tx.type === 'Income' ? 'bg-emerald-500/10 text-emerald-400' : 'bg-coral-500/10 text-coral-400')}>
                      {tx.type === 'Income' ? <ArrowDownRight className="w-5 h-5"/> : <ArrowUpRight className="w-5 h-5"/>}
                    </div>
                    <div className="min-w-0">
                      <p className="font-medium text-sm truncate w-32 md:w-auto">{tx.title}</p>
                      <p className="text-xs text-slate-500">{tx.category} • {format(parseISO(tx.date), 'MMM d')}</p>
                    </div>
                  </div>
                  <div className={cn("font-mono font-medium whitespace-nowrap", tx.type === 'Income' ? 'text-emerald-400' : 'text-slate-200')}>
                    {tx.type === 'Income' ? '+' : '-'}{formatCurrency(tx.amount, settings.currency)}
                  </div>
                </div>
              ))}
              {transactions.length === 0 && <EmptyState message="No recent transactions" />}
            </div>
            <button onClick={() => setTab('Transactions')} className="w-full mt-4 py-2 text-sm text-slate-400 hover:text-white transition-colors border border-slate-800 rounded-lg hover:bg-slate-800">
              View All History
            </button>
         </div>
      </div>
    </div>
  );
}

// Helpers for components
function SummaryCard({title, amount, trend, isPositive, currency, icon: Icon}: any) {
  return (
     <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 relative overflow-hidden group hover:border-slate-700 transition-all">
       <div className="flex justify-between items-start">
         <span className="text-sm text-slate-400 font-medium tracking-wide">{title}</span>
         <Icon className={cn("w-5 h-5", isPositive ? 'text-emerald-500' : 'text-coral-500')} />
       </div>
       <div className="mt-4 break-all pr-4">
         <div className={cn("text-3xl font-mono font-semibold tracking-tight", isPositive ? 'text-white' : 'text-slate-100')}>
           {formatCurrency(amount, currency)}
         </div>
       </div>
       {/* Fake sparkline logic using CSS for visuals only */}
       <div className="absolute bottom-0 left-0 w-full h-1 bg-gradient-to-r from-transparent via-slate-700 to-transparent opacity-0 group-hover:opacity-100 transition-opacity"></div>
     </div>
  );
}

function EmptyState({message}: {message: string}) {
  return (
     <div className="flex flex-col items-center justify-center p-8 text-center h-full opacity-60">
        <FileText className="w-12 h-12 text-slate-600 mb-4" />
        <p className="text-slate-400">{message}</p>
     </div>
  );
}

// Extract chart data helpers
function getDailyCashflowProps(transactions: Transaction[]) {
  // Return last 14 days
  const today = new Date();
  const days = eachDayOfInterval({start: subDays(today, 13), end: today});
  return days.map(day => {
    const dayStr = format(day, 'yyyy-MM-dd');
    const dayTxs = transactions.filter(t => t.date.startsWith(dayStr));
    const inc = dayTxs.filter(t => t.type === 'Income').reduce((a, b) => a + b.amount, 0);
    const exp = dayTxs.filter(t => t.type === 'Expense').reduce((a, b) => a + b.amount, 0);
    return { date: format(day, 'MMM d'), Income: inc, Expense: exp };
  });
}

// Rest of components will be added next...
`;
fs.writeFileSync('/src/App.tsx', code);
