import { supabase } from '../lib/supabase';
import type { Transaction, Budget, Task, User } from '../App';

export async function syncUser(email: string, name: string): Promise<User | null> {
  try {
    // 1. Check if user already exists
    const { data: existing, error: fetchErr } = await supabase
      .from('users')
      .select('*')
      .eq('email', email)
      .maybeSingle();

    if (fetchErr) throw fetchErr;

    if (existing) {
      return {
        id: existing.id,
        name: existing.name,
        email: existing.email,
        joinedDate: existing.created_at,
      };
    }

    // 2. Otherwise create a new profile
    const userId = 'usr-' + Math.random().toString(36).substring(2, 11);
    const { data: created, error: createErr } = await supabase
      .from('users')
      .insert([{ id: userId, name, email }])
      .select()
      .single();

    if (createErr) throw createErr;

    return {
      id: created.id,
      name: created.name,
      email: created.email,
      joinedDate: created.created_at,
    };
  } catch (err) {
    console.error('Supabase syncUser failed, using local fallback:', err);
    return null;
  }
}

export async function fetchTransactions(userId: string): Promise<Transaction[] | null> {
  try {
    const { data, error } = await supabase
      .from('transactions')
      .select('*')
      .eq('user_id', userId);

    if (error) throw error;

    return (data || []).map((t: any) => ({
      id: t.id,
      type: t.type as 'Income' | 'Expense',
      amount: Number(t.amount),
      category: t.category,
      title: t.title,
      date: t.date,
      paymentMethod: t.payment_method as any,
      notes: t.notes || undefined,
      recurring: !!t.recurring,
      recurringFrequency: t.recurring_frequency || undefined,
      tags: t.tags || [],
    }));
  } catch (err) {
    console.error('Supabase fetchTransactions failed:', err);
    return null;
  }
}

export async function saveTransaction(userId: string, tx: Transaction): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('transactions')
      .upsert({
        id: tx.id,
        user_id: userId,
        type: tx.type,
        amount: tx.amount,
        category: tx.category,
        title: tx.title,
        date: tx.date,
        payment_method: tx.paymentMethod,
        notes: tx.notes || null,
        recurring: tx.recurring,
        recurring_frequency: tx.recurringFrequency || null,
        tags: tx.tags || [],
      });

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Supabase saveTransaction failed:', err);
    return false;
  }
}

export async function deleteTransaction(txId: string): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('transactions')
      .delete()
      .eq('id', txId);

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Supabase deleteTransaction failed:', err);
    return false;
  }
}

export async function fetchBudgets(userId: string): Promise<Budget[] | null> {
  try {
    const { data, error } = await supabase
      .from('budgets')
      .select('category, limit')
      .eq('user_id', userId);

    if (error) throw error;
    return (data || []).map((b: any) => ({
      category: b.category,
      limit: Number(b.limit),
    }));
  } catch (err) {
    console.error('Supabase fetchBudgets failed:', err);
    return null;
  }
}

export async function saveBudget(userId: string, budget: Budget): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('budgets')
      .upsert({
        user_id: userId,
        category: budget.category,
        limit: budget.limit,
      }, { onConflict: 'user_id,category' });

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Supabase saveBudget failed:', err);
    return false;
  }
}

export async function fetchTasks(userId: string): Promise<Task[] | null> {
  try {
    const { data, error } = await supabase
      .from('tasks')
      .select('*')
      .eq('user_id', userId);

    if (error) throw error;
    return (data || []).map((t: any) => ({
      id: t.id,
      title: t.title,
      priority: t.priority as any,
      dueDate: t.due_date,
      status: t.status as any,
      isAutoGenerated: !!t.is_auto_generated,
    }));
  } catch (err) {
    console.error('Supabase fetchTasks failed:', err);
    return null;
  }
}

export async function saveTask(userId: string, task: Task): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('tasks')
      .upsert({
        id: task.id,
        user_id: userId,
        title: task.title,
        priority: task.priority,
        due_date: task.dueDate,
        status: task.status,
        is_auto_generated: !!task.isAutoGenerated,
      });

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Supabase saveTask failed:', err);
    return false;
  }
}

export async function deleteTask(taskId: string): Promise<boolean> {
  try {
    const { error } = await supabase
      .from('tasks')
      .delete()
      .eq('id', taskId);

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('Supabase deleteTask failed:', err);
    return false;
  }
}
