import React, { useState, useEffect, useMemo, useRef } from 'react';
import { 
  LineChart, Line, BarChart, Bar, PieChart, Pie, Cell, AreaChart, Area, 
  XAxis, YAxis, CartesianGrid, Tooltip as RechartsTooltip, Legend, ResponsiveContainer, ReferenceLine
} from 'recharts';
import { 
  Bell, Check, ChevronDown, Edit2, Eye, EyeOff, LayoutDashboard, ListTodo,
  LogOut, PieChart as PieChartIcon, Plus, Search, Settings as SettingsIcon, Target, Trash2,
  TrendingDown, TrendingUp, Upload, Download, Wallet, AlertCircle, Calendar,
  CreditCard, DollarSign, ArrowUpRight, ArrowDownRight, Activity, FileText,
  Filter, Tag, ChevronsUpDown, CheckCircle2, Clock, X, Circle, HelpCircle,
  Lightbulb, AlertTriangle, ShieldCheck, Menu, MoreHorizontal
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  format, subDays, subMonths, isSameMonth, parseISO, isAfter, isBefore, 
  startOfMonth, endOfMonth, eachDayOfInterval, formatDistanceToNow, isFuture, getDay, startOfWeek, addDays, isValid, parse
} from 'date-fns';
import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

import { checkSupabaseConnection, type SupabaseStatus } from './services/dbDiagnostic';
import { 
  syncUser, fetchTransactions, fetchBudgets, fetchTasks, 
  saveTransaction, deleteTransaction, saveBudget, saveTask, deleteTask 
} from './services/dbSync';

// ==========================================
// TYPES
// ==========================================
export type TransactionType = 'Income' | 'Expense';
export type PaymentMethod = 'Cash' | 'Bank Transfer' | 'Credit Card' | 'Debit Card' | 'Mobile Wallet' | 'Cheque' | 'Other';

export interface Transaction {
  id: string;
  type: TransactionType;
  amount: number;
  category: string;
  title: string;
  date: string; // ISO
  paymentMethod: PaymentMethod;
  notes?: string;
  recurring: boolean;
  recurringFrequency?: 'Daily' | 'Weekly' | 'Monthly' | 'Yearly';
  tags: string[];
}

export interface User { id: string; name: string; email: string; joinedDate: string; }
export interface Budget { category: string; limit: number; }
export interface Task { id: string; title: string; priority: 'Low' | 'Medium' | 'High'; dueDate: string; status: 'Pending' | 'In Progress' | 'Done'; isAutoGenerated?: boolean; }
export interface SettingsConfig { currency: string; dateFormat: string; theme: 'Dark' | 'Light' | 'System'; defaultView: string; alertThreshold: number; budgetAlerts: boolean; categories: { income: string[]; expense: string[] }; }
export interface Notification { id: string; message: string; date: string; read: boolean; type: 'info' | 'warning' | 'success'; }

// ==========================================
// CONSTANTS & DEMO DATA
// ==========================================
export const DEFAULT_INCOME_CATS = ['Salary', 'Freelance', 'Business', 'Investment Returns', 'Rental Income', 'Gift', 'Bonus', 'Other Income'];
export const DEFAULT_EXPENSE_CATS = ['Food & Dining', 'Transport', 'Housing/Rent', 'Utilities', 'Healthcare', 'Education', 'Entertainment', 'Shopping', 'Personal Care', 'Savings/Investment', 'Subscriptions', 'Travel', 'Debt Payment', 'Other Expense'];
export const CURRENCIES = ['PKR ₨', 'USD $', 'EUR €', 'GBP £', 'SAR ﷼', 'AED د.إ.'];

const generateDemoData = () => {
  const txs: Transaction[] = [];
  const today = new Date();
  for (let i = 0; i < 180; i++) {
    const date = subDays(today, i);
    const dateStr = date.toISOString();
    if (i % 30 === 0) {
      txs.push({ id: `demo-inc-${i}`, type: 'Income', amount: 150000, category: 'Salary', title: 'Monthly Salary', date: dateStr, paymentMethod: 'Bank Transfer', recurring: true, recurringFrequency: 'Monthly', tags: ['work'] });
    }
    txs.push({ id: `demo-food-${i}`, type: 'Expense', amount: 500 + Math.floor(Math.random() * 2000), category: 'Food & Dining', title: 'Groceries/Meals', date: dateStr, paymentMethod: 'Credit Card', recurring: false, tags: ['daily'] });
    if (i % 3 === 0) {
      txs.push({ id: `demo-trans-${i}`, type: 'Expense', amount: 300 + Math.floor(Math.random() * 1000), category: 'Transport', title: 'Fuel/Ride', date: dateStr, paymentMethod: 'Mobile Wallet', recurring: false, tags: ['commute'] });
    }
    if (i % 30 === 5) {
      txs.push({ id: `demo-rent-${i}`, type: 'Expense', amount: 40000, category: 'Housing/Rent', title: 'Rent Payment', date: dateStr, paymentMethod: 'Bank Transfer', recurring: true, recurringFrequency: 'Monthly', tags: ['housing'] });
      txs.push({ id: `demo-util-${i}`, type: 'Expense', amount: 12000, category: 'Utilities', title: 'Electricity & Water', date: dateStr, paymentMethod: 'Bank Transfer', recurring: true, recurringFrequency: 'Monthly', tags: ['bills'] });
    }
    if (i % 30 === 10) {
      txs.push({ id: `demo-sub-${i}`, type: 'Expense', amount: 1500, category: 'Subscriptions', title: 'Netflix', date: dateStr, paymentMethod: 'Credit Card', recurring: true, recurringFrequency: 'Monthly', tags: ['fun'] });
      txs.push({ id: `demo-sub2-${i}`, type: 'Expense', amount: 800, category: 'Subscriptions', title: 'Spotify', date: dateStr, paymentMethod: 'Credit Card', recurring: true, recurringFrequency: 'Monthly', tags: ['fun'] });
    }
    if (i % 14 === 0) {
      txs.push({ id: `demo-ent-${i}`, type: 'Expense', amount: 3000 + Math.floor(Math.random() * 5000), category: 'Entertainment', title: 'Movie & Dinner', date: dateStr, paymentMethod: 'Debit Card', recurring: false, tags: ['fun'] });
    }
  }
  return txs;
};

export const formatCurrency = (amount: number, currency: string) => {
  const symbol = currency.split(' ')[1] || '$';
  return `${amount < 0 ? '-' : ''}${symbol}${Math.abs(amount).toLocaleString('en-US', { minimumFractionDigits: 0, maximumFractionDigits: 2 })}`;
};

export const COLORS = {
  income: '#10b981', // emerald-500
  expense: '#f43f5e', // coral-500
  accent: '#f59e0b', // amber-500
};

const CHART_COLORS = ['#34d399', '#60a5fa', '#a78bfa', '#fb7185', '#fcd34d', '#2dd4bf'];

// ==========================================
// COMPONENTS
// ==========================================
export default function App() {
  const [user, setUser] = useState<User | null>(null);
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const [budgets, setBudgets] = useState<Budget[]>([
    { category: 'Food & Dining', limit: 25000 },
    { category: 'Transport', limit: 10000 },
    { category: 'Entertainment', limit: 8000 }
  ]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [settings, setSettings] = useState<SettingsConfig>({
    currency: 'PKR ₨',
    dateFormat: 'dd/MM/yyyy',
    theme: 'Dark',
    defaultView: 'Dashboard',
    alertThreshold: 1000000,
    budgetAlerts: true,
    categories: { income: DEFAULT_INCOME_CATS, expense: DEFAULT_EXPENSE_CATS }
  });

  const [activeTab, setActiveTab] = useState('Dashboard');
  const [isAuthMode, setIsAuthMode] = useState<'Login' | 'Register'>('Login');
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  
  // Modals state
  const [isTxModalOpen, setIsTxModalOpen] = useState(false);
  const [editingTx, setEditingTx] = useState<Transaction | null>(null);
  const [toasts, setToasts] = useState<{id: string, msg: string, type: 'success'|'error'|'info'}[]>([]);

  const [dbStatus, setDbStatus] = useState<SupabaseStatus | null>(null);
  const [isValidatingDb, setIsValidatingDb] = useState(false);

  const addToast = (msg: string, type: 'success'|'error'|'info' = 'info') => {
    const id = Math.random().toString(36).substring(2, 11);
    setToasts(prev => [...prev, {id, msg, type}]);
    setTimeout(() => setToasts(prev => prev.filter(t => t.id !== id)), 4000);
  };

  const checkDb = async (showToast = false) => {
    setIsValidatingDb(true);
    try {
      const status = await checkSupabaseConnection();
      setDbStatus(status);
      if (showToast) {
        if (status.connected && Object.values(status.tables).every(Boolean)) {
          addToast('Connected to Supabase! Direct sync is active.', 'success');
        } else if (status.connected) {
          addToast('Connected to Supabase. Note: Some tables are missing.', 'info');
        } else if (!status.configured) {
          addToast('Supabase is not configured yet. Add your project credentials/secrets!', 'info');
        } else {
          addToast(status.error || 'Connection verification failed.', 'error');
        }
      }
      return status;
    } catch {
      if (showToast) addToast('Failed to check database connection.', 'error');
      return null;
    } finally {
      setIsValidatingDb(false);
    }
  };

  useEffect(() => {
    checkDb();
    // Auto-login from local storage state if a previous session exists
    const stored = localStorage.getItem('finflow_user_session');
    if (stored) {
      try {
        const u = JSON.parse(stored);
        setUser(u);
        
        // Fetch database parameters in background
        checkSupabaseConnection().then(async (status) => {
          setDbStatus(status);
          if (status.connected) {
            if (status.tables.transactions) {
              const txs = await fetchTransactions(u.id);
              if (txs) setTransactions(txs);
            }
            if (status.tables.budgets) {
              const bg = await fetchBudgets(u.id);
              if (bg && bg.length > 0) setBudgets(bg);
            }
            if (status.tables.tasks) {
              const tk = await fetchTasks(u.id);
              if (tk) setTasks(tk);
            }
          }
        });
      } catch (e) {
        console.error('Session restore failed:', e);
      }
    }
  }, []);

  const loginDemo = () => {
    const demoUser = { id: 'demo123', name: 'Alex Demo', email: 'alex@finflow.demo', joinedDate: new Date().toISOString() };
    setUser(demoUser);
    localStorage.setItem('finflow_user_session', JSON.stringify(demoUser));
    setTransactions(generateDemoData());
    addToast('Logged in with Demo Account (offline storage only)', 'success');
  };

  const handleAuth = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const data = new FormData(e.currentTarget);
    const email = data.get('email') as string;
    const name = (data.get('name') as string) || 'New User';
    
    addToast('Checking backend database status...', 'info');
    const status = await checkDb();
    
    if (status && status.connected && status.tables.users) {
      addToast('Verifying session on Supabase...', 'info');
      const synced = await syncUser(email, name);
      if (synced) {
        setUser(synced);
        localStorage.setItem('finflow_user_session', JSON.stringify(synced));
        
        let txsLoaded = false;
        if (status.tables.transactions) {
          const txs = await fetchTransactions(synced.id);
          if (txs) {
            setTransactions(txs);
            txsLoaded = true;
          }
        }
        if (status.tables.budgets) {
          const bg = await fetchBudgets(synced.id);
          if (bg && bg.length > 0) setBudgets(bg);
        }
        if (status.tables.tasks) {
          const tk = await fetchTasks(synced.id);
          if (tk) setTasks(tk);
        }
        
        if (txsLoaded) {
          addToast(`Successfully loaded historic data from Supabase!`, 'success');
        } else {
          addToast(`Signed in and synced securely to Supabase!`, 'success');
        }
        return;
      }
    }
    
    // Offline local fallback
    const localUser = { id: 'usr-'+Date.now(), name, email, joinedDate: new Date().toISOString() };
    setUser(localUser);
    localStorage.setItem('finflow_user_session', JSON.stringify(localUser));
    if(transactions.length === 0) setTransactions([]);
    addToast(`Running in fallback local sandbox mode.`, 'info');
  };

  const logout = () => {
    setUser(null);
    localStorage.removeItem('finflow_user_session');
    setTransactions([]);
    setTasks([]);
    addToast('Logged out successfully', 'info');
  };

  const handleSetBudgets = async (newBudgets: Budget[] | ((prev: Budget[]) => Budget[])) => {
    let resolvedBudgets: Budget[];
    if (typeof newBudgets === 'function') {
      setBudgets(prev => {
        resolvedBudgets = newBudgets(prev);
        if (user && dbStatus?.connected && dbStatus?.tables.budgets) {
          resolvedBudgets.forEach(b => saveBudget(user.id, b));
        }
        return resolvedBudgets;
      });
    } else {
      resolvedBudgets = newBudgets;
      setBudgets(resolvedBudgets);
      if (user && dbStatus?.connected && dbStatus?.tables.budgets) {
        resolvedBudgets.forEach(b => saveBudget(user.id, b));
      }
    }
  };

  const handleSetTasks = async (newTasks: Task[] | ((prev: Task[]) => Task[])) => {
    let resolvedTasks: Task[];
    if (typeof newTasks === 'function') {
      setTasks(prev => {
        resolvedTasks = newTasks(prev);
        if (user && dbStatus?.connected && dbStatus?.tables.tasks) {
          const deleted = prev.filter(p => !resolvedTasks.some(r => r.id === p.id));
          deleted.forEach(d => deleteTask(d.id));
          resolvedTasks.forEach(k => saveTask(user.id, k));
        }
        return resolvedTasks;
      });
    } else {
      resolvedTasks = newTasks;
      const prev = tasks;
      setTasks(resolvedTasks);
      if (user && dbStatus?.connected && dbStatus?.tables.tasks) {
        const deleted = prev.filter(p => !resolvedTasks.some(r => r.id === p.id));
        deleted.forEach(d => deleteTask(d.id));
        resolvedTasks.forEach(k => saveTask(user.id, k));
      }
    }
  };

  const thisMonthTxs = useMemo(() => {
    const today = new Date();
    return transactions.filter(t => {
      try {
        const d = parseISO(t.date);
        return d.getMonth() === today.getMonth() && d.getFullYear() === today.getFullYear();
      } catch { return false; }
    });
  }, [transactions]);

  const totalIncome = useMemo(() => transactions.filter(t => t.type === 'Income').reduce((a, b) => a + b.amount, 0), [transactions]);
  const totalExpense = useMemo(() => transactions.filter(t => t.type === 'Expense').reduce((a, b) => a + b.amount, 0), [transactions]);
  const netBalance = totalIncome - totalExpense;

  const monthlyIncome = useMemo(() => thisMonthTxs.filter(t => t.type === 'Income').reduce((a, b) => a + b.amount, 0), [thisMonthTxs]);
  const monthlyExpense = useMemo(() => thisMonthTxs.filter(t => t.type === 'Expense').reduce((a, b) => a + b.amount, 0), [thisMonthTxs]);
  const savingsRate = monthlyIncome > 0 ? ((monthlyIncome - monthlyExpense) / monthlyIncome) * 100 : 0;

  const bottomActiveTab = useMemo(() => {
    if (['Insights', 'Tasks', 'Settings', 'More'].includes(activeTab)) {
      return 'More';
    }
    return activeTab;
  }, [activeTab]);

  if (!user) {
    return <AuthScreen isAuthMode={isAuthMode} setIsAuthMode={setIsAuthMode} handleAuth={handleAuth} loginDemo={loginDemo} toasts={toasts} />;
  }

  const hour = new Date().getHours();
  const greeting = hour < 12 ? 'Good morning' : hour < 18 ? 'Good afternoon' : 'Good evening';

  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex font-body pb-16 md:pb-0">
      <aside className="w-64 bg-slate-850 border-r border-slate-800 hidden md:flex flex-col animate-in slide-in-from-left duration-200">
        <div className="p-6 flex items-center gap-3">
          <div className="w-8 h-8 flex items-center justify-center bg-emerald-500 rounded-lg">
            <Wallet className="w-5 h-5 text-slate-900" />
          </div>
          <span className="font-display font-bold text-xl tracking-tight text-white">FinFlow</span>
        </div>
        <nav className="flex-1 px-4 space-y-1 mt-4">
          <NavItem id="Dashboard" icon={LayoutDashboard} label="Dashboard" activeTab={activeTab} setActiveTab={setActiveTab} />
          <NavItem id="Transactions" icon={ListTodo} label="Transactions" activeTab={activeTab} setActiveTab={setActiveTab} />
          <NavItem id="Charts" icon={PieChartIcon} label="Charts & Analytics" activeTab={activeTab} setActiveTab={setActiveTab} />
          <NavItem id="Insights" icon={Lightbulb} label="AI Insights" activeTab={activeTab} setActiveTab={setActiveTab} />
          <NavItem id="Budgets" icon={Target} label="Budget Planner" activeTab={activeTab} setActiveTab={setActiveTab} />
          <NavItem id="Tasks" icon={CheckCircle2} label="Goals & Tasks" activeTab={activeTab} setActiveTab={setActiveTab} />
        </nav>
        <div className="p-4 border-t border-slate-800">
           <NavItem id="Settings" icon={SettingsIcon} label="Settings" activeTab={activeTab} setActiveTab={setActiveTab} />
        </div>
      </aside>

      <main className="flex-1 flex flex-col h-screen overflow-hidden">
        <header className="h-16 border-b border-slate-800 bg-slate-850/50 backdrop-blur-md flex items-center justify-between px-4 md:px-6 shrink-0 z-10 w-full animate-in fade-in duration-200">
          <div className="flex items-center gap-3">
            {/* Elegant compact logo indicator for mobile instead of manual slide triggers */}
            <div className="w-8 h-8 flex items-center justify-center bg-emerald-500 rounded-lg md:hidden">
              <Wallet className="w-5 h-5 text-slate-900" />
            </div>
            <h2 className="text-base md:text-lg font-medium text-slate-200 truncate">{greeting}, {user.name.split(' ')[0]} 👋</h2>
          </div>
          <div className="flex items-center gap-4">
            <button className="relative p-2 text-slate-400 hover:text-slate-200 transition-colors">
              <Bell className="w-5 h-5" />
            </button>
            <div className="h-6 w-px bg-slate-700"></div>
            <div className="flex items-center gap-3 group cursor-pointer" onClick={logout}>
              <div className="w-8 h-8 rounded-full bg-slate-700 flex items-center justify-center text-sm font-medium">{user.name.charAt(0).toUpperCase()}</div>
              <LogOut className="w-4 h-4 text-slate-500 group-hover:text-coral-400 transition-colors" />
            </div>
          </div>
        </header>

        <div className="flex-1 overflow-auto p-4 md:p-8">
           <div className="max-w-7xl mx-auto space-y-8">
             {activeTab === 'Dashboard' && <DashboardView user={user} transactions={transactions} settings={settings} monthlyIncome={monthlyIncome} monthlyExpense={monthlyExpense} netBalance={netBalance} savingsRate={savingsRate} setTab={setActiveTab} onOpenTx={() => {setEditingTx(null); setIsTxModalOpen(true);}} />}
             {activeTab === 'Transactions' && <TransactionsView transactions={transactions} settings={settings} onAdd={() => {setEditingTx(null); setIsTxModalOpen(true)}} onEdit={(tx: Transaction) => {setEditingTx(tx); setIsTxModalOpen(true)}} onDelete={async (id: string) => {
               setTransactions(prev => prev.filter(t => t.id !== id)); 
               addToast('Transaction deleted', 'success');
               if (user && dbStatus?.connected && dbStatus?.tables.transactions) {
                 await deleteTransaction(id);
               }
             }} />}
             {activeTab === 'Charts' && <ChartsView transactions={transactions} settings={settings} />}
             {activeTab === 'Insights' && <InsightsView transactions={transactions} settings={settings} />}
             {activeTab === 'Budgets' && <BudgetsView transactions={transactions} settings={settings} budgets={budgets} setBudgets={handleSetBudgets} />}
             {activeTab === 'Tasks' && <TasksView transactions={transactions} tasks={tasks} setTasks={handleSetTasks} />}
             {activeTab === 'Settings' && <SettingsView settings={settings} setSettings={setSettings} user={user} setTransactions={setTransactions} addToast={addToast} dbStatus={dbStatus} isValidatingDb={isValidatingDb} onCheckDb={checkDb} />}
             {activeTab === 'More' && <MoreView setTab={setActiveTab} logout={logout} user={user} />}
           </div>
        </div>
      </main>

      <AnimatePresence>
        {isTxModalOpen && <TransactionModal editingTx={editingTx} settings={settings} onClose={() => setIsTxModalOpen(false)} onSave={async (tx: Transaction) => {
            if (editingTx) { 
              setTransactions(prev => prev.map(t => t.id === tx.id ? tx : t)); 
              addToast('Transaction updated', 'success'); 
            } else { 
              setTransactions(prev => [tx, ...prev].sort((a,b)=> new Date(b.date).getTime() - new Date(a.date).getTime())); 
              addToast('Transaction added', 'success'); 
            }
            setIsTxModalOpen(false);
            if (user && dbStatus?.connected && dbStatus?.tables.transactions) {
              await saveTransaction(user.id, tx);
            }
          }} />}
      </AnimatePresence>

      {/* Mobile Bottom Navigation Bar */}
      <div className="md:hidden fixed bottom-0 left-0 right-0 h-16 bg-slate-850/95 backdrop-blur-md border-t border-slate-800/80 flex items-center justify-around px-2 z-30 pb-safe">
        <BottomTabItem id="Dashboard" icon={LayoutDashboard} label="Overview" activeTab={bottomActiveTab} setActiveTab={setActiveTab} />
        <BottomTabItem id="Transactions" icon={ListTodo} label="History" activeTab={bottomActiveTab} setActiveTab={setActiveTab} />
        <BottomTabItem id="Charts" icon={PieChartIcon} label="Analytics" activeTab={bottomActiveTab} setActiveTab={setActiveTab} />
        <BottomTabItem id="Budgets" icon={Target} label="Budgets" activeTab={bottomActiveTab} setActiveTab={setActiveTab} />
        <BottomTabItem id="More" icon={MoreHorizontal} label="More" activeTab={bottomActiveTab} setActiveTab={setActiveTab} />
      </div>

      <div className="fixed bottom-20 md:bottom-4 right-4 z-50 flex flex-col gap-2">
        <AnimatePresence>
          {toasts.map(t => (
            <motion.div key={t.id} initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} exit={{opacity:0, scale:0.95}} className={cn("px-4 py-3 rounded-xl shadow-lg border flex items-center gap-3", t.type === 'success' ? 'bg-emerald-500/10 border-emerald-500/20 text-emerald-400' : t.type === 'error' ? 'bg-coral-500/10 border-coral-500/20 text-coral-400' : 'bg-slate-800 border-slate-700 text-slate-200')}>
              {t.type === 'success' ? <CheckCircle2 className="w-5 h-5"/> : t.type==='error' ? <AlertCircle className="w-5 h-5"/> : <Bell className="w-5 h-5"/>} {t.msg}
            </motion.div>
          ))}
        </AnimatePresence>
      </div>
    </div>
  );
}

function NavItem({ id, icon: Icon, label, activeTab, setActiveTab }: { id: string, icon: any, label: string, activeTab: string, setActiveTab: (id: string) => void }) {
  return (
    <button onClick={() => setActiveTab(id)} className={cn("flex items-center gap-3 w-full px-4 py-3 rounded-xl transition-all text-left", activeTab === id ? 'bg-emerald-500/10 text-emerald-400 font-medium' : 'text-slate-400 hover:bg-slate-800/50 hover:text-slate-200')}>
      <Icon className="w-5 h-5" />{label}
    </button>
  );
}

function BottomTabItem({ id, icon: Icon, label, activeTab, setActiveTab }: { id: string, icon: any, label: string, activeTab: string, setActiveTab: (id: string) => void }) {
  const active = activeTab === id;
  return (
    <button 
      onClick={() => setActiveTab(id)} 
      className={cn("flex flex-col items-center justify-center gap-1 transition-all w-12 py-1", active ? 'text-emerald-400 font-medium scale-105' : 'text-slate-400 hover:text-slate-200')}
    >
      <Icon className="w-5 h-5" />
      <span className="text-[10px] whitespace-nowrap">{label}</span>
    </button>
  );
}

function MoreView({ setTab, logout, user }: { setTab: (tab: string) => void, logout: () => void, user: any }) {
  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      <div>
        <h1 className="text-2xl font-display font-semibold text-white">More Services</h1>
        <p className="text-slate-400 text-sm mt-1">Explore all additional FinFlow capabilities</p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {/* AI Insights Card */}
        <button 
          onClick={() => setTab('Insights')}
          className="flex items-start gap-4 p-5 rounded-2xl bg-slate-850 border border-slate-800 hover:border-emerald-500/40 hover:bg-emerald-500/5 transition-all text-left group"
        >
          <div className="p-3 bg-emerald-500/10 text-emerald-400 rounded-xl group-hover:scale-105 transition-transform shrink-0">
            <Lightbulb className="w-6 h-6" />
          </div>
          <div>
            <h3 className="font-semibold text-white group-hover:text-emerald-400 transition-colors">AI Insights</h3>
            <p className="text-xs text-slate-400 mt-1 leading-relaxed">Get smart automated tips, budget recommendations, and custom summaries generated from your actual dataset.</p>
          </div>
        </button>

        {/* Goals & Tasks Card */}
        <button 
          onClick={() => setTab('Tasks')}
          className="flex items-start gap-4 p-5 rounded-2xl bg-slate-850 border border-slate-800 hover:border-indigo-500/40 hover:bg-indigo-500/5 transition-all text-left group"
        >
          <div className="p-3 bg-indigo-500/10 text-indigo-400 rounded-xl group-hover:scale-105 transition-transform shrink-0">
            <CheckCircle2 className="w-6 h-6" />
          </div>
          <div>
            <h3 className="font-semibold text-white group-hover:text-indigo-400 transition-colors">Goals & Tasks</h3>
            <p className="text-xs text-slate-400 mt-1 leading-relaxed">Track financial milestones, upcoming utility bill checks, and checklist priorities aligned with your budgets.</p>
          </div>
        </button>

        {/* Settings Card */}
        <button 
          onClick={() => setTab('Settings')}
          className="flex items-start gap-4 p-5 rounded-2xl bg-slate-850 border border-slate-800 hover:border-amber-500/40 hover:bg-amber-500/5 transition-all text-left group"
        >
          <div className="p-3 bg-amber-500/10 text-amber-500 rounded-xl group-hover:scale-105 transition-transform shrink-0">
            <SettingsIcon className="w-6 h-6" />
          </div>
          <div>
            <h3 className="font-semibold text-white group-hover:text-amber-400 transition-colors">Settings</h3>
            <p className="text-xs text-slate-400 mt-1 leading-relaxed">Customize currency formats, budget alert limits, default categories, and handle database actions cleanly.</p>
          </div>
        </button>

        {/* Sign Out Card */}
        <button 
          onClick={logout}
          className="flex items-start gap-4 p-5 rounded-2xl bg-slate-850 border border-slate-800 hover:border-rose-500/40 hover:bg-rose-500/5 transition-all text-left group"
        >
          <div className="p-3 bg-rose-500/10 text-rose-400 rounded-xl group-hover:scale-105 transition-transform shrink-0">
            <LogOut className="w-6 h-6" />
          </div>
          <div>
            <h3 className="font-semibold text-white group-hover:text-rose-400 transition-colors">Sign Out</h3>
            <p className="text-xs text-slate-400 mt-1 leading-relaxed">Log out of this application session securely. Your configurations will be preserved safely.</p>
          </div>
        </button>
      </div>
    </div>
  );
}

// ==========================================
// VIEWS
// ==========================================
function AuthScreen({ isAuthMode, setIsAuthMode, handleAuth, loginDemo, toasts }: any) {
  const [password, setPassword] = useState('');
  return (
    <div className="min-h-screen bg-slate-900 text-slate-100 flex items-center justify-center p-4">
      <div className="max-w-md w-full bg-slate-850 p-8 rounded-2xl shadow-2xl border border-slate-800">
        <div className="text-center mb-8">
           <div className="w-16 h-16 bg-emerald-500/10 rounded-2xl mx-auto flex items-center justify-center mb-4">
             <Wallet className="w-8 h-8 text-emerald-500" />
           </div>
           <h1 className="text-3xl font-display font-bold text-white tracking-tight">FinFlow</h1>
           <p className="text-slate-400 mt-2">Take control of your financial future.</p>
        </div>
        <form onSubmit={handleAuth} className="space-y-4">
          <div className="flex bg-slate-800 p-1 rounded-lg mb-6">
             <button type="button" onClick={() => setIsAuthMode('Login')} className={cn("flex-1 py-2 text-sm font-medium rounded-md transition-all", isAuthMode === 'Login' ? 'bg-slate-700 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200')}>Login</button>
             <button type="button" onClick={() => setIsAuthMode('Register')} className={cn("flex-1 py-2 text-sm font-medium rounded-md transition-all", isAuthMode === 'Register' ? 'bg-slate-700 text-white shadow-sm' : 'text-slate-400 hover:text-slate-200')}>Register</button>
          </div>
          {isAuthMode === 'Register' && (
            <div>
              <label className="block text-sm text-slate-400 mb-1">Full Name</label>
              <input required name="name" type="text" className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500" placeholder="Jane Doe" />
            </div>
          )}
          <div>
            <label className="block text-sm text-slate-400 mb-1">Email</label>
            <input required name="email" type="email" className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500" placeholder="jane@example.com" />
          </div>
          <div>
            <label className="block text-sm text-slate-400 mb-1">Password</label>
            <input required name="password" minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500" placeholder="••••••••" />
            {isAuthMode === 'Register' && password.length > 0 && (
               <div className="mt-2 text-xs text-slate-400">Password strength: {password.length > 8 ? 'Strong' : 'Weak'}</div>
            )}
          </div>
          {isAuthMode === 'Register' && (
             <div>
               <label className="block text-sm text-slate-400 mb-1">Confirm Password</label>
               <input required name="confirmPassword" minLength={8} type="password" pattern={password} title="Passwords must match" className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500" placeholder="••••••••" />
             </div>
          )}
          <button type="submit" className="w-full bg-emerald-500 hover:bg-emerald-600 text-slate-900 font-bold py-3 rounded-xl transition-all shadow-lg shadow-emerald-500/20 mt-4">
            {isAuthMode === 'Login' ? 'Sign In' : 'Create Account'}
          </button>
        </form>
        <div className="mt-8 relative">
          <div className="absolute inset-0 flex items-center"><div className="w-full border-t border-slate-800"></div></div>
          <div className="relative flex justify-center text-xs text-slate-500"><span className="bg-slate-850 px-2">OR</span></div>
        </div>
        <button onClick={loginDemo} type="button" className="w-full mt-6 bg-slate-800 hover:bg-slate-700 text-slate-200 font-medium py-3 rounded-xl transition-all border border-slate-700 flex items-center justify-center gap-2">
          <Activity className="w-4 h-4" /> Try Demo Account
        </button>
      </div>
    </div>
  );
}

function DashboardView({ user, transactions, settings, monthlyIncome, monthlyExpense, netBalance, savingsRate, setTab, onOpenTx }: any) {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-display font-semibold">Overview</h1>
        <button onClick={onOpenTx} className="bg-emerald-500 hover:bg-emerald-600 text-slate-900 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors">
          <Plus className="w-4 h-4" /> Add Record
        </button>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <SummaryCard title="Total Balance" amount={netBalance} isPositive={netBalance >= 0} currency={settings.currency} icon={Wallet} />
        <SummaryCard title="Monthly Income" amount={monthlyIncome} isPositive={true} currency={settings.currency} icon={TrendingUp} />
        <SummaryCard title="Monthly Expenses" amount={monthlyExpense} isPositive={false} currency={settings.currency} icon={TrendingDown} />
        <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 relative overflow-hidden flex flex-col justify-between">
          <div className="flex justify-between items-start">
            <span className="text-sm text-slate-400 font-medium padding-wide">Savings Rate</span>
            <Target className="w-5 h-5 text-amber-500" />
          </div>
          <div className="mt-4 text-3xl font-mono font-semibold text-white">{savingsRate.toFixed(1)}%</div>
        </div>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
         <div className="bg-slate-850 shrink-0 p-6 rounded-2xl border border-slate-800 lg:col-span-2 shadow-sm min-h-[400px] flex flex-col">
            <div className="flex justify-between items-center mb-6">
               <h3 className="text-lg font-medium">Recent Cash Flow</h3>
               <button onClick={() => setTab('Charts')} className="text-sm text-emerald-400 hover:text-emerald-300">View detailed</button>
            </div>
            <div className="flex-1 w-full relative">
              {transactions.length === 0 ? <EmptyState message="No transactions to chart" /> : (
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={getDailyCashflowProps(transactions)}>
                    <defs>
                      <linearGradient id="colorInc" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={COLORS.income} stopOpacity={0.3}/><stop offset="95%" stopColor={COLORS.income} stopOpacity={0}/></linearGradient>
                      <linearGradient id="colorExp" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={COLORS.expense} stopOpacity={0.3}/><stop offset="95%" stopColor={COLORS.expense} stopOpacity={0}/></linearGradient>
                    </defs>
                    <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
                    <XAxis dataKey="date" stroke="#475569" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis stroke="#475569" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(v) => `${v/1000}k`} />
                    <RechartsTooltip contentStyle={{backgroundColor: '#0f172a', borderColor: '#1e293b', borderRadius: '8px'}} itemStyle={{fontFamily: 'IBM Plex Mono'}} />
                    <Area type="monotone" dataKey="Income" stroke={COLORS.income} fillOpacity={1} fill="url(#colorInc)" />
                    <Area type="monotone" dataKey="Expense" stroke={COLORS.expense} fillOpacity={1} fill="url(#colorExp)" />
                  </AreaChart>
                </ResponsiveContainer>
              )}
            </div>
         </div>
         <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 shadow-sm flex flex-col">
            <h3 className="text-lg font-medium mb-4">Recent Transactions</h3>
            <div className="space-y-4 flex-1 overflow-y-auto pr-2">
              {transactions.slice(0, 7).map((tx: Transaction) => (
                <div key={tx.id} className="flex justify-between items-center bg-slate-900/50 p-3 rounded-xl border border-slate-800/80">
                  <div className="flex gap-3 items-center">
                    <div className={cn("w-10 h-10 rounded-full flex items-center justify-center shrink-0", tx.type === 'Income' ? 'bg-emerald-500/10 text-emerald-400' : 'bg-coral-500/10 text-coral-400')}>
                      {tx.type === 'Income' ? <ArrowDownRight className="w-5 h-5"/> : <ArrowUpRight className="w-5 h-5"/>}
                    </div>
                    <div className="min-w-0">
                      <p className="font-medium text-sm truncate">{tx.title}</p>
                      <p className="text-xs text-slate-500">{tx.category}</p>
                    </div>
                  </div>
                  <div className={cn("font-mono font-medium whitespace-nowrap", tx.type === 'Income' ? 'text-emerald-400' : 'text-slate-200')}>
                    {tx.type === 'Income' ? '+' : '-'}{formatCurrency(tx.amount, settings.currency)}
                  </div>
                </div>
              ))}
              {transactions.length === 0 && <EmptyState message="No recent transactions" />}
            </div>
         </div>
      </div>
    </div>
  );
}

function TransactionsView({ transactions, settings, onAdd, onEdit, onDelete }: any) {
  const [search, setSearch] = useState('');
  const [filterType, setFilterType] = useState('All');
  const filtered = transactions.filter((t: Transaction) => {
    if (filterType !== 'All' && t.type !== filterType) return false;
    if (search && !t.title.toLowerCase().includes(search.toLowerCase()) && !t.category.toLowerCase().includes(search.toLowerCase())) return false;
    return true;
  });

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-display font-semibold">Transactions</h1>
        <button onClick={onAdd} className="bg-emerald-500 hover:bg-emerald-600 text-slate-900 px-4 py-2 rounded-lg font-medium flex items-center gap-2 transition-colors">
          <Plus className="w-4 h-4" /> Add Record
        </button>
      </div>
      <div className="flex gap-4 mb-4 flex-wrap">
        <div className="flex-1 min-w-[200px] relative">
          <Search className="absolute left-3 top-2.5 w-4 h-4 text-slate-500" />
          <input type="text" placeholder="Search..." value={search} onChange={e=>setSearch(e.target.value)} className="w-full bg-slate-850 border border-slate-700 rounded-lg pl-9 pr-4 py-2 text-sm focus:border-emerald-500 outline-none" />
        </div>
        <select value={filterType} onChange={e=>setFilterType(e.target.value)} className="bg-slate-850 border border-slate-700 rounded-lg px-4 py-2 text-sm outline-none">
           <option value="All">All Types</option>
           <option value="Income">Income</option>
           <option value="Expense">Expense</option>
        </select>
      </div>
      <div className="bg-slate-850 rounded-2xl border border-slate-800 overflow-hidden">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-900/50 text-slate-400 text-sm border-b border-slate-800">
              <th className="p-4 font-medium">Date</th>
              <th className="p-4 font-medium">Title</th>
              <th className="p-4 font-medium hidden md:table-cell">Category</th>
              <th className="p-4 font-medium text-right">Amount</th>
              <th className="p-4 font-medium text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((tx: Transaction) => (
              <tr key={tx.id} className="border-b border-slate-800 hover:bg-slate-800/50 transition-colors">
                <td className="p-4 text-sm text-slate-300">
                  {format(parseISO(tx.date), 'MMM dd, yyyy')}
                </td>
                <td className="p-4">
                  <div className="font-medium text-slate-200">{tx.title}</div>
                  <div className="text-xs text-slate-500 md:hidden">{tx.category}</div>
                </td>
                <td className="p-4 hidden md:table-cell">
                  <span className={cn("px-2 py-1 rounded text-xs", tx.type==='Income'?'bg-emerald-500/10 text-emerald-400':'bg-slate-700 text-slate-300')}>{tx.category}</span>
                </td>
                <td className={cn("p-4 text-right font-mono font-medium", tx.type==='Income' ? 'text-emerald-400':'text-slate-200')}>
                  {tx.type === 'Income' ? '+' : '-'}{formatCurrency(tx.amount, settings.currency)}
                </td>
                <td className="p-4">
                  <div className="flex justify-center gap-2">
                    <button onClick={() => onEdit(tx)} className="p-2 text-slate-400 hover:text-white rounded hover:bg-slate-700"><Edit2 className="w-4 h-4"/></button>
                    <button onClick={() => { if(confirm('Delete this transaction?')) onDelete(tx.id); }} className="p-2 text-slate-400 hover:text-coral-500 rounded hover:bg-coral-500/10"><Trash2 className="w-4 h-4"/></button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        {filtered.length === 0 && <EmptyState message="No transactions found" />}
      </div>
    </div>
  );
}

function ChartsView({ transactions, settings }: any) {
  const incExpData = useMemo(() => {
    const res: Record<string, any> = {};
    transactions.forEach((t: Transaction) => {
      const month = format(parseISO(t.date), 'MMM yyyy');
      if(!res[month]) res[month] = { name: month, Income: 0, Expense: 0 };
      res[month][t.type] += t.amount;
    });
    return Object.values(res).reverse();
  }, [transactions]);

  const catData = useMemo(() => {
    const cats: Record<string, number> = {};
    transactions.filter((t: Transaction) => t.type === 'Expense').forEach(t => { cats[t.category] = (cats[t.category] || 0) + t.amount; });
    return Object.keys(cats).map(k => ({ name: k, value: cats[k] })).sort((a,b)=>b.value-a.value);
  }, [transactions]);

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-display font-semibold">Charts & Analytics</h1>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 min-h-[350px]">
          <h3 className="text-lg font-medium mb-6">Income vs Expense</h3>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={incExpData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" vertical={false} />
              <XAxis dataKey="name" stroke="#475569" fontSize={12} />
              <YAxis stroke="#475569" fontSize={12} tickFormatter={v=>`${v/1000}k`} />
              <RechartsTooltip contentStyle={{backgroundColor: '#0f172a', borderColor: '#1e293b'}} />
              <Legend />
              <Bar dataKey="Income" fill={COLORS.income} radius={[4,4,0,0]} />
              <Bar dataKey="Expense" fill={COLORS.expense} radius={[4,4,0,0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>
        <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 min-h-[350px]">
          <h3 className="text-lg font-medium mb-6">Spending by Category</h3>
          {catData.length > 0 ? (
            <ResponsiveContainer width="100%" height={300}>
              <PieChart>
                <Pie data={catData} innerRadius={80} outerRadius={110} paddingAngle={2} dataKey="value">
                  {catData.map((e, i) => <Cell key={i} fill={CHART_COLORS[i % CHART_COLORS.length]} />)}
                </Pie>
                <RechartsTooltip contentStyle={{backgroundColor: '#0f172a', borderColor: '#1e293b'}} formatter={(v) => formatCurrency(v as number, settings.currency)} />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          ) : <EmptyState message="Not enough data" />}
        </div>
      </div>
    </div>
  );
}

function InsightsView({ transactions, settings }: any) {
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-display font-semibold">AI Insights</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800">
           <div className="flex items-center gap-3 text-emerald-400 mb-2">
             <ShieldCheck className="w-5 h-5"/> <h3 className="font-medium">Savings Health</h3>
           </div>
           <p className="text-slate-300">Your savings rate has improved by 4% compared to last month. Keep up the good work!</p>
        </div>
        <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800">
           <div className="flex items-center gap-3 text-amber-500 mb-2">
             <AlertTriangle className="w-5 h-5"/> <h3 className="font-medium">Top Drain</h3>
           </div>
           <p className="text-slate-300">Food & Dining consumed 34% of your expenses this month. Consider cooking more often.</p>
        </div>
        <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800">
           <div className="flex items-center gap-3 text-blue-400 mb-2">
             <Clock className="w-5 h-5"/> <h3 className="font-medium">Recurring Audit</h3>
           </div>
           <p className="text-slate-300">You have 6 active subscriptions totaling {formatCurrency(4200, settings.currency)}/month. Review them soon.</p>
        </div>
      </div>
    </div>
  );
}

function BudgetsView({ budgets, setBudgets, transactions, settings }: any) {
  const [newCat, setNewCat] = useState(settings.categories.expense[0] || '');
  const [newLim, setNewLim] = useState('');
  
  const addBudget = () => {
    if(!newCat || !newLim) return;
    setBudgets((prev: Budget[]) => [...prev.filter(b=>b.category !== newCat), {category: newCat, limit: Number(newLim)}]);
    setNewLim('');
  };

  const currentMonthExp = transactions.filter((t: Transaction) => t.type==='Expense' && isSameMonth(parseISO(t.date), new Date()));

  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-display font-semibold">Budget Planner</h1>
      <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800">
        <div className="flex gap-4 mb-6 form-row">
          <select value={newCat} onChange={e=>setNewCat(e.target.value)} className="bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 flex-1">
             {settings.categories.expense.map((c: string) => <option key={c} value={c}>{c}</option>)}
          </select>
          <input type="number" placeholder="Limit Amount" value={newLim} onChange={e=>setNewLim(e.target.value)} className="bg-slate-900 border border-slate-700 rounded-lg px-4 py-2 w-32" />
          <button onClick={addBudget} className="bg-emerald-500 hover:bg-emerald-600 text-slate-900 px-4 py-2 rounded-lg font-medium">Set</button>
        </div>
        
        <div className="space-y-6">
          {budgets.map((b: Budget) => {
            const spent = currentMonthExp.filter((t: Transaction) => t.category === b.category).reduce((a:number, b:any) => a+b.amount, 0);
            const pct = Math.min((spent / b.limit) * 100, 100);
            const isOver = spent > b.limit;
            return (
              <div key={b.category}>
                <div className="flex justify-between mb-2 text-sm">
                  <span className="font-medium text-slate-200">{b.category}</span>
                  <span>{formatCurrency(spent, settings.currency)} / {formatCurrency(b.limit, settings.currency)}</span>
                </div>
                <div className="h-2 w-full bg-slate-700 rounded-full overflow-hidden">
                  <div className={cn("h-full transition-all text-right", isOver ? 'bg-coral-500' : pct > 80 ? 'bg-amber-500' : 'bg-emerald-500')} style={{width: `${pct}%`}}></div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

function TasksView({ tasks, setTasks }: any) {
  const [val, setVal] = useState('');
  const addT = () => { if(!val) return; setTasks([{id: Date.now().toString(), title: val, status: 'Pending', priority: 'Medium'}, ...tasks]); setVal(''); };
  return (
    <div className="space-y-6">
      <h1 className="text-2xl font-display font-semibold">Goals & Priorities</h1>
      <div className="flex gap-4">
        <input value={val} onChange={e=>setVal(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addT()} placeholder="New goal or task..." className="bg-slate-850 flex-1 px-4 py-3 rounded-xl border border-slate-700 outline-none focus:border-emerald-500" />
        <button onClick={addT} className="bg-emerald-500 hover:bg-emerald-600 px-6 py-3 rounded-xl text-slate-900 font-bold">Add</button>
      </div>
      <div className="space-y-2">
        {tasks.map((t: Task) => (
          <div key={t.id} className="bg-slate-850 p-4 rounded-xl border border-slate-800 flex justify-between items-center">
            <div className="flex items-center gap-3 text-slate-200">
               <button onClick={()=>setTasks(tasks.map((k:any)=>k.id===t.id?{...k,status:k.status==='Done'?'Pending':'Done'}:k))} className={cn("w-5 h-5 rounded border flex items-center justify-center", t.status==='Done'?'bg-emerald-500 border-emerald-500':'border-slate-500')}>
                 {t.status==='Done' && <Check className="w-3 h-3 text-slate-900"/>}
               </button>
               <span className={cn(t.status==='Done'&&'line-through text-slate-500')}>{t.title}</span>
            </div>
            <button onClick={()=>setTasks(tasks.filter((k:any)=>k.id!==t.id))} className="text-slate-500 hover:text-coral-500"><Trash2 className="w-4 h-4"/></button>
          </div>
        ))}
      </div>
    </div>
  );
}

function SettingsView({ settings, setSettings, user, setTransactions, addToast, dbStatus, isValidatingDb, onCheckDb }: any) {
  const reset = () => { if(confirm('Permanently delete all transactions? Type DELETE to confirm.')){ setTransactions([]); addToast('All data cleared', 'info') } };
  const [showSql, setShowSql] = useState(false);

  const copySql = () => {
    if (dbStatus?.sqlSchema) {
      navigator.clipboard.writeText(dbStatus.sqlSchema);
      addToast('SQL Migration Schema copied to clipboard!', 'success');
    }
  };

  return (
    <div className="space-y-6 max-w-2xl">
      <h1 className="text-2xl font-display font-semibold text-white">Settings</h1>
      
      {/* Basic Settings */}
      <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 space-y-6">
        <div>
          <label className="block text-sm text-slate-400 mb-2 font-medium">Currency</label>
          <select value={settings.currency} onChange={e=>setSettings({...settings, currency: e.target.value})} className="w-full bg-slate-900 border border-slate-700 rounded-lg px-4 py-3 outline-none focus:border-emerald-500 text-slate-200">
             {CURRENCIES.map(c => <option key={c} value={c}>{c}</option>)}
          </select>
        </div>
        <div>
          <label className="block text-sm text-slate-400 mb-2 font-medium">My Profile</label>
          <div className="bg-slate-900 p-4 rounded-xl border border-slate-700 flex items-center gap-4">
             <div className="w-12 h-12 bg-emerald-500/10 text-emerald-400 rounded-full flex items-center justify-center font-bold text-lg">{user.name[0]?.toUpperCase()}</div>
             <div>
               <div className="font-medium text-white">{user.name}</div>
               <div className="text-xs text-slate-500 mt-0.5">{user.email}</div>
             </div>
          </div>
        </div>
        <div className="pt-4 border-t border-slate-800 flex justify-between items-center">
          <button onClick={reset} className="text-rose-400 text-sm font-medium hover:underline flex items-center gap-2">
            <Trash2 className="w-4 h-4" /> Reset All Local Transactions
          </button>
        </div>
      </div>

      {/* Database Diagnostic Center */}
      <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 space-y-6">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-base font-semibold text-white flex items-center gap-2">
              <ShieldCheck className="w-5 h-5 text-emerald-400" /> Database Integration (Supabase)
            </h3>
            <p className="text-xs text-slate-400 mt-1">Connect the applet dynamically to real persistence</p>
          </div>
          <button 
            onClick={() => onCheckDb(true)} 
            disabled={isValidatingDb}
            className="px-3 py-1.5 text-xs font-semibold bg-slate-800 text-slate-200 hover:bg-slate-700 rounded-lg transition-all border border-slate-700 duration-150 flex items-center gap-1.5"
          >
            <Activity className={cn("w-3.5 h-3.5", isValidatingDb && "animate-spin")} />
            {isValidatingDb ? 'Testing...' : 'Test Connection'}
          </button>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div className="bg-slate-900 p-4 rounded-xl border border-slate-850 space-y-2">
            <div className="text-xs text-slate-550">Connection Status</div>
            <div className="flex items-center gap-2">
              {dbStatus?.connected ? (
                <>
                  <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
                  <span className="text-sm font-medium text-slate-200">Connected to Supabase</span>
                </>
              ) : (
                <>
                  <span className="w-2.5 h-2.5 rounded-full bg-slate-500"></span>
                  <span className="text-sm font-medium text-slate-450">
                    {dbStatus?.configured ? 'Credential issues' : 'Running in local sandbox'}
                  </span>
                </>
              )}
            </div>
            {dbStatus?.error && (
              <p className="text-[11px] text-rose-400 pt-1 leading-normal italic">{dbStatus.error}</p>
            )}
            {!dbStatus?.configured && !dbStatus?.error && (
              <p className="text-[11px] text-slate-400 leading-normal">
                No secrets detected. Set secrets <strong className="text-emerald-400">VITE_SUPABASE_URL</strong> and <strong className="text-emerald-400">VITE_SUPABASE_ANON_KEY</strong> in the Secrets/Settings panel to activate sync.
              </p>
            )}
          </div>

          <div className="bg-slate-900 p-4 rounded-xl border border-slate-850 space-y-2">
            <div className="text-xs text-slate-550">Table Assertions (Supabase Schema)</div>
            <div className="grid grid-cols-2 gap-2 text-xs">
              <div className="flex items-center gap-1.5">
                {dbStatus?.tables.users ? (
                  <Check className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                ) : (
                  <X className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                )}
                <span className="text-slate-300 font-mono">users</span>
              </div>
              <div className="flex items-center gap-1.5">
                {dbStatus?.tables.transactions ? (
                  <Check className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                ) : (
                  <X className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                )}
                <span className="text-slate-300 font-mono">transactions</span>
              </div>
              <div className="flex items-center gap-1.5">
                {dbStatus?.tables.budgets ? (
                  <Check className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                ) : (
                  <X className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                )}
                <span className="text-slate-300 font-mono">budgets</span>
              </div>
              <div className="flex items-center gap-1.5">
                {dbStatus?.tables.tasks ? (
                  <Check className="w-3.5 h-3.5 text-emerald-400 shrink-0" />
                ) : (
                  <X className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                )}
                <span className="text-slate-300 font-mono">tasks</span>
              </div>
            </div>
          </div>
        </div>

        {dbStatus?.connected && !Object.values(dbStatus.tables).every(Boolean) && (
          <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-xl space-y-2">
            <div className="flex items-start gap-2 text-amber-500 text-xs font-semibold">
              <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>Database Table Schema Missing</span>
            </div>
            <p className="text-[11px] text-slate-300 leading-relaxed">
              We connected to your Supabase instance, but couldn't locate the required relational tables. Please write or execute the database structure script inside your Supabase dashboard.
            </p>
            <div className="pt-2 flex gap-3">
              <button 
                onClick={() => setShowSql(!showSql)} 
                className="text-xs text-amber-400 font-semibold hover:underline flex items-center gap-1"
              >
                <FileText className="w-3.5 h-3.5" /> {showSql ? 'Hide SQL Code' : 'View Migration SQL'}
              </button>
              <button 
                onClick={copySql} 
                className="text-xs text-slate-200 font-semibold hover:underline flex items-center gap-1"
              >
                <Check className="w-3.5 h-3.5 text-emerald-500" /> Copy Config SQL
              </button>
            </div>

            {showSql && (
              <div className="mt-3 relative">
                <pre className="text-[10px] font-mono bg-slate-950 p-4 rounded-lg overflow-x-auto text-slate-300 max-h-48 border border-slate-800">
                  {dbStatus.sqlSchema}
                </pre>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

// ==========================================
// MODALS
// ==========================================

function TransactionModal({ editingTx, settings, onClose, onSave }: any) {
  const [type, setType] = useState<TransactionType>(editingTx ? editingTx.type : 'Expense');
  const [amount, setAmount] = useState(editingTx ? editingTx.amount.toString() : '');
  const [category, setCategory] = useState(editingTx ? editingTx.category : settings.categories.expense[0]);
  const [title, setTitle] = useState(editingTx ? editingTx.title : '');
  const [date, setDate] = useState(editingTx ? editingTx.date.split('T')[0] : format(new Date(), 'yyyy-MM-dd'));
  const [pm, setPm] = useState(editingTx ? editingTx.paymentMethod : 'Cash');
  const [notes, setNotes] = useState(editingTx ? editingTx.notes : '');

  const save = (e: React.FormEvent) => {
    e.preventDefault();
    if(!title || !amount || Number(amount) <= 0) return;
    onSave({
      id: editingTx ? editingTx.id : 'tx-'+Date.now(), type, amount: Number(amount), category, title,
      date: new Date(date).toISOString(), paymentMethod: pm, recurring: false, tags: [], notes
    });
  };

  const cats = type === 'Income' ? settings.categories.income : settings.categories.expense;
  useEffect(() => { if(!editingTx) setCategory(cats[0]); }, [type, cats, editingTx]);

  return (
    <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <motion.div initial={{scale:0.95, opacity:0}} animate={{scale:1, opacity:1}} exit={{scale:0.95, opacity:0}} className="bg-slate-850 w-full max-w-lg rounded-2xl shadow-2xl border border-slate-700 overflow-hidden">
        <div className="flex justify-between items-center p-6 border-b border-slate-800">
          <h3 className="text-xl font-display font-semibold">{editingTx ? 'Edit' : 'Add'} Transaction</h3>
          <button onClick={onClose}><X className="w-5 h-5 text-slate-400 hover:text-white" /></button>
        </div>
        <form onSubmit={save} className="p-6 space-y-4">
          <div className="flex bg-slate-900 p-1 rounded-lg">
             <button type="button" onClick={()=>setType('Income')} className={cn("flex-1 py-2 text-sm font-medium rounded-md", type === 'Income' ? 'bg-emerald-500 text-slate-900 shadow-sm' : 'text-slate-400')}>Income</button>
             <button type="button" onClick={()=>setType('Expense')} className={cn("flex-1 py-2 text-sm font-medium rounded-md", type === 'Expense' ? 'bg-coral-500 text-white shadow-sm' : 'text-slate-400')}>Expense</button>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm text-slate-400 mb-1">Amount</label>
              <input required type="number" step="0.01" min="0" value={amount} onChange={e=>setAmount(e.target.value)} className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500 text-lg font-mono" placeholder="0.00" />
            </div>
            <div>
              <label className="block text-sm text-slate-400 mb-1">Date</label>
              <input required type="date" value={date} max={format(new Date(), 'yyyy-MM-dd')} onChange={e=>setDate(e.target.value)} className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500" />
            </div>
          </div>
          <div>
            <label className="block text-sm text-slate-400 mb-1">Title</label>
            <input required type="text" maxLength={100} value={title} onChange={e=>setTitle(e.target.value)} className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500" placeholder="e.g. Groceries" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm text-slate-400 mb-1">Category</label>
              <select value={category} onChange={e=>setCategory(e.target.value)} className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500">
                {cats.map((c: string) => <option key={c} value={c}>{c}</option>)}
              </select>
            </div>
            <div>
              <label className="block text-sm text-slate-400 mb-1">Payment Method</label>
              <select value={pm} onChange={e=>setPm(e.target.value)} className="w-full bg-slate-900 border border-slate-700 rounded-xl px-4 py-3 outline-none focus:border-emerald-500">
                {["Cash", "Bank Transfer", "Credit Card", "Debit Card", "Mobile Wallet", "Cheque", "Other"].map(m=><option key={m} value={m}>{m}</option>)}
              </select>
            </div>
          </div>
          <button type="submit" className={cn("w-full font-bold py-4 rounded-xl transition-all text-lg mt-4 shadow-lg", type === 'Income' ? 'bg-emerald-500 hover:bg-emerald-600 text-slate-900 shadow-emerald-500/20' : 'bg-coral-500 hover:bg-coral-600 text-white shadow-coral-500/20')}>
            {editingTx ? 'Save Changes' : 'Add Transaction'}
          </button>
        </form>
      </motion.div>
    </div>
  );
}

function SummaryCard({title, amount, trend, isPositive, currency, icon: Icon}: any) {
  return (
     <div className="bg-slate-850 p-6 rounded-2xl border border-slate-800 relative overflow-hidden group hover:border-slate-700 transition-all">
       <div className="flex justify-between items-start">
         <span className="text-sm text-slate-400 font-medium tracking-wide">{title}</span>
         <Icon className={cn("w-5 h-5", isPositive ? 'text-emerald-500' : 'text-coral-500')} />
       </div>
       <div className="mt-4 break-all pr-4">
         <div className={cn("text-3xl font-mono font-semibold tracking-tight", isPositive ? 'text-white' : 'text-slate-100')}>
           {formatCurrency(amount, currency)}
         </div>
       </div>
     </div>
  );
}

function EmptyState({message}: {message: string}) {
  return (
     <div className="flex flex-col items-center justify-center p-8 text-center h-full opacity-60">
        <FileText className="w-12 h-12 text-slate-600 mb-4" />
        <p className="text-slate-400">{message}</p>
     </div>
  );
}

function getDailyCashflowProps(transactions: Transaction[]) {
  const today = new Date();
  const days = eachDayOfInterval({start: subDays(today, 13), end: today});
  return days.map(day => {
    const dayStr = format(day, 'yyyy-MM-dd');
    const dayTxs = transactions.filter(t => t.date.startsWith(dayStr));
    const inc = dayTxs.filter(t => t.type === 'Income').reduce((a, b) => a + b.amount, 0);
    const exp = dayTxs.filter(t => t.type === 'Expense').reduce((a, b) => a + b.amount, 0);
    return { date: format(day, 'MMM d'), Income: inc, Expense: exp };
  });
}
